# Generated by Django 5.0.2 on 2024-02-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
    ]
